import cv2 as cv

color_d = {
    "AUTUMN" : cv.COLORMAP_AUTUMN,
    "BONE" : cv.COLORMAP_BONE,
    "JET" : cv.COLORMAP_JET,
    "WINTER" : cv.COLORMAP_WINTER,
    "RAINBOW" : cv.COLORMAP_RAINBOW,
    "OCEAN" : cv.COLORMAP_OCEAN,
    "SUMMER" : cv.COLORMAP_SUMMER,
    "SPRING" : cv.COLORMAP_SPRING,
    "COOL" : cv.COLORMAP_COOL,
    "HSV" : cv.COLORMAP_HSV,
    "PINK" : cv.COLORMAP_PINK,
    "HOT" : cv.COLORMAP_HOT,
    "PARULA" : cv.COLORMAP_PARULA,
    "MAGMA" : cv.COLORMAP_MAGMA,
    "INFERNO" : cv.COLORMAP_INFERNO,
    "PLASMA" : cv.COLORMAP_PLASMA,
    "VIRIDIS" : cv.COLORMAP_VIRIDIS,
    "CIVIDIS" : cv.COLORMAP_CIVIDIS,
    "TWILIGHT" : cv.COLORMAP_TWILIGHT,
    "TWILIGHT_SHIFTED" : cv.COLORMAP_TWILIGHT_SHIFTED,
    "TURBO" : cv.COLORMAP_TURBO,
    "DEEPGREEN" : cv.COLORMAP_DEEPGREEN
}